# Usamos la imagen oficial de MongoDB como base
FROM mongo:7.0

# Puedes opcionalmente añadir scripts de inicialización o configuraciones extra aquí
# por ejemplo:
# COPY ./init-db.js /docker-entrypoint-initdb.d/

# Puerto por defecto de MongoDB
EXPOSE 27017
